import ChatWidget from "../ChatWidget";
import { SiteFooter, SiteHeader } from "./SiteChrome";
import "../products.css";

export function MotionRelayTermsPage() {
  return <main className="products-page privacy-page"><SiteHeader /><section className="products-hero studio-wrap"><div><p className="eyebrow">Motion Relay</p><h1>Terms of Service.</h1></div><div className="products-hero-copy"><p>These terms govern Motion Relay accounts, phone apps, connector access and related services provided by Netherwood Data Partners.</p><p className="privacy-updated">Effective October 3, 2026.</p></div></section><section className="privacy-content studio-wrap">
    <article><h2>1. Agreement and eligibility</h2><p>By creating a Motion Relay account or affirmatively accepting these terms, you agree to them and the <a href="/privacy/motion-relay/">Motion Relay Privacy Notice</a>. If you do not agree, do not use Motion Relay. You must be at least 18 years old and legally able to enter this agreement.</p></article>
    <article><h2>2. What Motion Relay does</h2><p>Motion Relay receives compatible fitness-activity measurements from supported devices, organizes a limited current-activity snapshot and, at your direction, makes that snapshot available to an assistant you select. Measurements and service behavior depend on the watch, sensors, activity, phone, network, permissions and third-party services.</p><p>Motion Relay does not guarantee that a measurement, connection, assistant response, estimate or service will always be accurate, current, continuous or available. Check the source device and use independent judgment.</p></article>
    <article><h2>3. Fitness, medical and emergency warning</h2><p>Motion Relay is for informational and recreational fitness purposes. It is not a medical device, medical advice, diagnosis, treatment, emergency monitoring or emergency response service. Automated assistant responses may be incorrect, incomplete, delayed or unavailable. Do not use Motion Relay to decide whether emergency care is needed. Stop activity and seek appropriate help for an emergency or alarming symptoms.</p></article>
    <article><h2>4. Activity and surroundings</h2><p>Physical activity involves risk. You are responsible for choosing an activity appropriate to your condition and environment, following traffic and facility rules, watching weather and terrain, and using phones and headphones safely. Motion Relay is not navigation, rescue service, a safety plan, an emergency contact or a substitute for attention to your surroundings.</p></article>
    <article><h2>5. Accounts and acceptable use</h2><p>You are responsible for devices and third-party accounts you connect and for revoking access to a lost, transferred or compromised device. You may not access another person’s data, share credentials, bypass feature limits, interfere with the service, reverse engineer access controls or use Motion Relay unlawfully. We may suspend access reasonably necessary to protect users, the service or third parties.</p></article>
    <article><h2>6. Sharing and third-party services</h2><p>Assistant sharing is optional. Garmin, Apple, Google, OpenAI, ChatGPT, app stores, networks and device manufacturers are independent services governed by their own terms and privacy controls. Motion Relay does not receive your Garmin, Apple, Google or ChatGPT password. Stopping Motion Relay sharing does not erase a third party’s conversation or account history.</p></article>
    <article><h2>7. Plans, subscriptions and billing</h2><p>Free and paid features are described at purchase. Digital subscriptions are purchased and managed through the applicable app store, which displays price, tax, renewal, trial, cancellation and refund terms. Deleting a Motion Relay account does not automatically cancel an app-store subscription; cancel it through the store. Complimentary and tester access is revocable and is not a paid store purchase.</p></article>
    <article><h2>8. Privacy and deletion</h2><p>The Privacy Notice explains Motion Relay data handling and controls. Live sharing, optional fitness context and completed-summary backup require separate choices. You can stop sharing, disconnect a phone and delete your authenticated account in the app. <a href="/privacy/motion-relay/delete/">External deletion instructions</a> remain available if the app is no longer installed.</p></article>
    <article><h2>9. Intellectual property</h2><p>Motion Relay software, documentation and branding are owned by Netherwood or its licensors and protected by applicable law. These terms provide a personal, limited, revocable, non-transferable right to use the service as offered. Third-party names and marks belong to their owners.</p></article>
    <article><h2>10. Service changes and termination</h2><p>We may modify, suspend or discontinue features to maintain security, comply with law or improve the service. We will provide notice or request renewed acceptance when applicable law requires it. You may stop using the service, cancel a store subscription and delete your Motion Relay account at any time.</p></article>
    <article><h2>11. Disclaimers</h2><p>To the fullest extent permitted by applicable law, Motion Relay is provided “as is” and “as available” without warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, continuity or safety. Some jurisdictions do not permit some exclusions, so those exclusions may not apply to you.</p></article>
    <article><h2>12. Limitation of liability</h2><p>To the fullest extent permitted by applicable law, Netherwood Data Partners and its owners, personnel and licensors will not be liable for indirect, incidental, special, consequential or punitive damages, or loss of data, revenue, profits or goodwill, arising from Motion Relay or third-party services. For claims lawfully subject to a monetary cap, aggregate liability will not exceed the greater of the amount you paid for Motion Relay during the 12 months before the event giving rise to the claim or US $100.</p><p>These terms do not exclude liability that cannot legally be excluded, including liability where applicable law prohibits a limitation for intentional misconduct, gross negligence, personal injury or consumer rights.</p></article>
    <article><h2>13. Responsibility for misuse</h2><p>You are responsible for losses and third-party claims caused by your unlawful misuse of Motion Relay, infringement of another person’s rights or material breach of these terms, to the extent permitted by law. This section does not require you to cover claims caused by Netherwood’s own unlawful conduct.</p></article>
    <article><h2>14. Governing law</h2><p>These terms are governed by the laws of New Jersey and applicable United States federal law, without regard to conflict-of-law rules. Courts located in New Jersey will have jurisdiction unless applicable consumer law gives you a different mandatory forum. Nothing here waives rights that cannot lawfully be waived.</p></article>
    <article><h2>15. Contact</h2><p>Questions about these terms may be sent to <a href="mailto:contact@NetherwoodDataPartners.com">contact@Netherwood<wbr />DataPartners.com</a>.</p></article>
  </section><SiteFooter /><ChatWidget /></main>;
}
