import ChatWidget from "../ChatWidget";
import { SiteFooter, SiteHeader } from "./SiteChrome";
import "../products.css";

export function MotionRelayPrivacyPage() {
  return <main className="products-page privacy-page"><SiteHeader /><section className="products-hero studio-wrap"><div><p className="eyebrow">Motion Relay</p><h1>Privacy notice.</h1></div><div className="products-hero-copy"><p>Motion Relay is a fitness companion operated by Netherwood Data Partners. This notice covers its iPhone and Android phone apps and Netherwood connector, not Garmin, ChatGPT or OpenAI accounts.</p><p className="privacy-updated">Effective October 3, 2026.</p></div></section><section className="privacy-content studio-wrap">
    <article><h2>1. Effective date and scope</h2><p>This notice applies to Motion Relay’s iPhone and Android companions, optional connector sharing and membership service. The Netherwood website’s general inquiry handling is described on the <a href="/privacy/">privacy index</a>.</p></article>
    <article><h2>2. Data Motion Relay handles</h2><p>Depending on your Garmin device, sensors and activity, current measurements can include heart rate, pace, speed, distance, elapsed time, cadence, power, altitude, oxygen saturation, calories, training effect and similar fitness metrics. Session identifiers, sequence numbers, activity state and timestamps help validate freshness and reject replays. The watch name or identifier is used locally for selection and excluded from connector telemetry.</p><p>Optional membership records can include your chosen nickname, a pseudonymous membership ID, plan, feature entitlements, consent state and credential-expiration metadata. Team or tester codes are processed only when you choose to redeem one. With separate backup consent, completed activity summaries can be stored in the Motion Relay SQL service.</p></article>
    <article><h2>3. Data Motion Relay does not request or retain</h2><p>The Android app does not request phone location, microphone, Health Connect, body-sensor or advertising-ID permission. The iPhone app can read the limited Apple Health fitness categories shown in its permission screen only after the user approves them; it requests no Health writes or workout routes. Both apps reject or remove GPS tracks, precise coordinates, destinations, device serial numbers and raw watch packets before optional sharing. The apps have no advertising or analytics SDK. Netherwood does not sell health or fitness data or use it for targeted advertising.</p></article>
    <article><h2>4. Purposes of processing</h2><p>Motion Relay displays available current-activity readings, checks their source and freshness, supports watch-to-phone delivery, and, when you choose, makes a redacted snapshot available to an authorized AI connection. Membership data supports access and consent choices. Optional completed-summary backup supports restoration and continuity.</p></article>
    <article><h2>5. Optional sharing and third parties</h2><p>Current-run connector sharing is off by default and needs your explicit action. Pairing the phone and authorizing ChatGPT are separate choices. If you authorize ChatGPT, the current snapshot may be retrieved through Netherwood’s connector by ChatGPT/OpenAI under their own terms and account settings. Stopping Motion Relay sharing does not erase ChatGPT conversation history. Garmin Connect, Connect IQ, Apple, Google, ChatGPT and OpenAI are separate services with separate terms and account controls.</p><p>Hosting and security providers process ordinary connection and security metadata needed to deliver and protect the service. Netherwood’s connector does not log fitness payloads during ordinary operation. Connector and tunnel container logs use bounded size-based rotation rather than a promised number of days. We retain provider and security records only as needed for operation, security, legal obligations and dispute handling.</p></article>
    <article><h2>6. Retention</h2><p>The Android companion holds current telemetry in volatile memory. On the running connector, the latest live snapshot expires after up to 90 seconds, rolling current-session samples after up to 20 minutes, and a completed summary after up to 30 minutes. In-memory replay/sequence state can remain until cleared or the connector restarts; a restart clears all current telemetry and replay state. Device and OAuth authorizations, and SQL membership and consent records, are persistent until revoked or deleted through the applicable process. Consented completed summaries persist until deletion; they are not the five-second live stream.</p></article>
    <article><h2>7. User controls</h2><p>You can leave connector sharing off, stop sharing, disconnect the phone, revoke its upload access and clear current snapshots from the app. You can choose whether completed-summary backup is enabled. Disconnecting is not account deletion.</p></article>
    <article><h2>8. Account and data deletion</h2><p>Authenticated users can permanently delete their Motion Relay account from Settings in the iPhone or Android app. Deletion revokes account-bound phone credentials, clears current connector snapshots and removes the nickname, membership, entitlements, consent state and retained completed summaries. A pseudonymized financial record may be retained when required for accounting, fraud prevention or legal obligations; it has no former public account ID, nickname, credential or fitness subject. The app returns a deletion receipt.</p><p><a href="/privacy/motion-relay/delete/">Use the external deletion-request page</a> if you no longer have the app. Netherwood must verify ownership before acting on an external request. Deleting Motion Relay data does not delete Garmin or ChatGPT accounts, Garmin data or ChatGPT conversation history.</p></article>
    <article><h2>9. Security</h2><p>Connector sharing uses authenticated HTTPS. Android stores its membership credential in device-protected app storage. Access to retained records is restricted; no security measure eliminates all risk.</p></article>
    <article><h2>10. Children and target audience</h2><p>Motion Relay is intended for adults managing their own fitness activities, not children.</p></article>
    <article><h2>11. Fitness, not medical</h2><p>Motion Relay is a fitness companion, not a medical device. It does not provide diagnosis, treatment or emergency monitoring.</p></article>
    <article><h2>12. Changes to this notice</h2><p>Material changes will be reflected here with a new effective date before the changed practices are used.</p></article>
    <article><h2>13. Contact and terms</h2><p>Email <a href="mailto:contact@NetherwoodDataPartners.com">contact@Netherwood<wbr />DataPartners.com</a> with privacy questions. Read the <a href="/terms/motion-relay/">Motion Relay Terms of Service</a>.</p></article>
  </section><SiteFooter /><ChatWidget /></main>;
}

export function MotionRelayDeletionPage() {
  return <main className="products-page privacy-page"><SiteHeader /><section className="products-hero studio-wrap"><div><p className="eyebrow">Motion Relay</p><h1>Delete your membership or account.</h1></div><div className="products-hero-copy"><p>This page is for Motion Relay by Netherwood Data Partners. You can start a deletion request here even if you no longer have the Android app installed.</p></div></section><section className="privacy-content studio-wrap">
    <article><h2>Delete in the app</h2><p>If you still have an authenticated Motion Relay account, open Settings and choose “Delete Motion Relay account.” Confirm the destructive action. The service revokes account-bound phone access, clears current connector snapshots, deletes linked account and fitness records, and returns a receipt. Disconnecting only the phone is a separate control and does not delete the account.</p></article>
    <article><h2>Start a request without the app</h2><p>Email <a href="mailto:contact@NetherwoodDataPartners.com?subject=Motion%20Relay%20membership%20deletion">contact@Netherwood<wbr />DataPartners.com</a> with the subject “Motion Relay membership deletion.” You may include the nickname you chose and an approximate registration date to help locate the record. Do not send a password, bearer token, invitation code, private health data or raw watch telemetry. We will provide a safe ownership-verification step; an unverified email alone cannot authorize deletion of someone else’s data.</p></article>
    <article><h2>What deletion covers</h2><p>Deletion removes the Motion Relay membership, nickname, credentials, entitlements, consent state, associated completed summaries and other linked personal records. A pseudonymized record may be retained only when required for accounting, fraud prevention, security or another legal obligation. Any retained record is separated from the former nickname, credential, fitness subject and public account identifier.</p></article>
    <article><h2>Separate services</h2><p>This request cannot delete a Garmin account, Garmin Connect data, a ChatGPT/OpenAI account or ChatGPT conversation history. Use those services’ own controls for their records. <a href="/privacy/motion-relay/">Read the Motion Relay privacy notice</a>.</p></article>
  </section><SiteFooter /><ChatWidget /></main>;
}
